# This is a basic workflow to help you get started with Actions

name: Manual-Workflow

# Set the workflow variable(s)
env:
  user_name: 'Test Elek'
  demo_name: 'Variable Demo'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' # because of 'set-env' disabled command

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'name of the person'
        required: true
        default: 'Thomas'
      country:
        description: 'name of the country'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set the job variable(s)
    env:
      job_var1: "This is job variable-1"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run a step with variables
        run: |
          echo "Hi ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.country }}"

      - name: Using workflow variables
        # Set the step variable(s)
        env:
          step_var1: "Set-Var-1"
        run: |
          echo "Hello, $user_name!"
          echo "Welcome to $demo_name!!!"
          echo "Job variable: $job_var1"
          echo "::set-env name=user_name::Odeeka"
          echo "::set-env name=new_user::Beluska"

      - name: Using the changed variables
        run: |
          echo "Changed user name: $user_name"
          echo "New user name: $new_user"
      - name: Print all environment variables
        run: |
          echo "Print all environment variables"
          env | sort